### ISSUE TITLE
Grid cell with "6 col" takes more then half of the width if content is large

### ISSUE THREAD

**Issue by ractive** [ajusa/lit#25]
Hi there

If not defining the column width with two columns or using "6 col", a cell with some larger content will take as much space as it needs. Other column widths than 6 work as expected.

See an example here;
https://www.w3schools.com/code/tryit.asp?filename=GETCRXX18RSO

**Comment by ajusa** [comment]
Wow uh... that's a bug. This is probably due to the way tables are used for the grid. I'll try moving the grid system to flexbox (seeing as it has a lot more support now) and that should fix the issue. I'll update and close the issue once I have fixed it.

**Comment by ractive** [comment]
Thanks. Keep up the good work. lit offers everything I need from a CSS framework... :-)

**Comment by ajusa** [comment]
This is now fixed with 6336fc1. Closing the issue for now.
I'm planning on working on this project more soon, so once other changes are done I'll make a release. Until a release happens, the example will be broken since it links to the latest release. If you want to test it (I did verify that your example works), you can download `dist/lit.css` in the repository.

**Comment by ractive** [comment]
It works, thanks! 👍
